#!/usr/bin/env python3

# Update versions
files = ["./abct-python/pyproject.toml", "./abct-matlab/matpackage.m"]
for file in files:
    with open(file, "r") as f:
        text = f.readlines()
        for i, line in enumerate(text):
            if line.startswith("version"):
                major, minor, patch = line.split("=")[1].strip().strip('"').split(".")
                text[i] = f'version = "{major}.{minor}.{int(patch) + 1}"\n'
                break
    with open(file, "w") as f:
        f.writelines(text)
