repos:
  - repo: local
    hooks:
    - id: sync-docstrings
      name: Sync docstrings
      entry: ./tools/sync_docstrings
      language: python
      stages: [pre-commit]
    - id: make-notebooks
      name: Make notebooks
      entry: ./tools/make_notebooks
      language: python
      stages: [pre-commit]
    - id: update-readme
      name: Update README.md
      entry: bash -c "cp $(cat /docs-code/index.qmd ./docs-code/installation.qmd) ./README.md"
      language: system
      stages: [pre-commit]