repos:
  - repo: local
    hooks:
    - id: sync-docstrings
      name: Sync docstrings
      entry: ./tools/sync_docstrings
      language: python
      stages: [pre-commit]
    - id: make-notebooks
      name: Make notebooks from qmd
      entry: ./tools/make_notebooks
      language: python
      stages: [pre-commit]
