repos:
  - repo: local
    hooks:
    - id: sync-docstrings
      name: Sync docstrings
      entry: ./tools/sync_docstrings
      language: python
      stages: [pre-commit]
    - id: render-docs
      name: Render docs
      entry: ./tools/render_docs
      language: python
      stages: [pre-commit]
