#!/usr/bin/env python3

import os
import glob

dir_matlab = "./abctmat"
dir_docs = "./abctpy/abct/docs"

for filename_mat in glob.glob(f"{dir_matlab}/*m"):
    with open(filename_mat, "r") as f:
        filetext = f.readlines()

    # parse the filetext to get the docstring
    for i, line in enumerate(filetext[1:]):
        if not line.strip().startswith("%"):
            break

    # get the docstring
    docstring = "".join([line[1:] for line in filetext[1:i+1]])
    docstring = docstring.replace("[", "").replace("]", "")

    # write the docstring
    filename_doc = filename_mat.replace(dir_matlab, dir_docs)[:-2]
    with open(filename_doc, "w") as f:
        f.write(docstring)
