project:                          # Project-level configuration
  type: website                   # Project type
  output-dir: ../docs             # Output directory

website:                          # Website-level configuration
  title: abct documentation       # The title displayed in the website header and tab
  site-url: https://mikarubi.github.io/abct/
  search: true                    # site-wide search index
  sidebar:
    contents: auto
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Installation"
        href: installation.qmd
      - text: "Example usage"
        href: examples.qmd
      - text: "Docstrings"
        href: docstrings.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true

execute:
  freeze: auto
  cache: true
