project:                          # Project-level configuration
  type: website                   # Project type
  output-dir: ../docs             # Output directory

website:                          # Website-level configuration
  title: abct documentation       # The title displayed in the website header and tab
  site-url: https://mikarubi.github.io/abct/
  search: true
  sidebar:
    contents: auto
    background: primary
    tools:
      - icon: github
        href: https://github.com/mikarubi/abct

  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    code-copy: true

execute:
  freeze: auto
  cache: true
