project:                          # Project-level configuration
  type: website                   # Project type
  render:
    - "*.qmd"
  output-dir: ../docs             # Output directory

website:                          # Website-level configuration
  title: abct documentation       # The title displayed in the website header and tab
  site-url: https://mikarubi.github.io/abct/
  page-navigation: true
  sidebar:
    search: true
    contents: auto

format:
  html:
    theme: sandstone
    code-fold: false
    code-copy: true

execute:
  freeze: auto
  cache: true
