project:                          # Project-level configuration
  type: website                   # Project type
  output-dir: ../docs             # Output directory

website:                          # Website-level configuration
  title: abct documentation       # The title displayed in the website header and tab
  site-url: https://mikarubi.github.io/abct/
  search: true                    # site-wide search index
  sidebar:
    contents: auto
  page-navigation: true

format:
  html:
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true

execute:
  freeze: auto
  cache: true
