#!/usr/bin/env python3

import os
import glob

dir_examples = "./docs-code/examples"
os.system(f"quarto render {dir_examples}")

qmd_files = glob.glob(f"{dir_examples}/*.qmd")
for qmd_file in qmd_files:
    os.system(f"quarto convert {qmd_file}")
