#!/usr/bin/env python3

import glob

dir_matlab = "./abct-matlab/abct/"
dir_docs = {"python": "./abct-python/abct/docstrings/doc_",
            "quarto": "./docs-code/functions/"}
ext_docs = {"python": ".py", 
            "quarto": ".qmd"}

filenames_mat = glob.glob(f"{dir_matlab}/*m")

for filename_mat in filenames_mat:
    with open(filename_mat, "r") as f:
        filetext = f.readlines()

    # parse the filetext to get the docstring
    for i, line in enumerate(filetext[1:]):
        if not line.strip().startswith("%"):
            break

    # get the docstring
    docstring = "".join([line[1:] for line in filetext[1:i+1]])
    docstring = "```\n" + docstring + "\n```\n"

    # write docstrings
    for typ in ["python", "quarto"]:
        filename_doc = filename_mat.\
            replace(dir_matlab, dir_docs[typ]).\
            replace(".m", ext_docs[typ])
        with open(filename_doc, "w") as f:
            f.write(docstring)
