#!/usr/bin/env python3

import os
from datetime import date

# Make archives
today = str(date.today())
os.system("rm ./abct-matlab.zip")
os.system("rm ./abct-python.zip")
os.system("touch ./v"+today)
os.system("zip -r abct-matlab.zip ./abct-matlab/abct ./abct-matlab/matpackage.m v"+today)
os.system("zip -r abct-python.zip ./abct-python/abct ./abct-python/pyproject.toml v"+today)
os.system("rm ./v"+today)

# Update versions
files = ["./abct-python/pyproject.toml", "./abct-matlab/matpackage.m"]
for file in files:
    with open(file, "r") as f:
        text = f.readlines()
        for i, line in enumerate(text):
            if line.startswith("version"):
                text[i] = f'version = "{today}"\n'
                break
    with open(file, "w") as f:
        f.writelines(text)
